name: Deploy to Firebase App Hosting

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy App Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase use example-cursor-v1 --token "$FIREBASE_TOKEN"
          firebase deploy --only apphosting --token "$FIREBASE_TOKEN"

# Prerequisites:
# 1) Enable App Hosting API: https://console.developers.google.com/apis/api/firebaseapphosting.googleapis.com/overview?project=example-cursor-v1
# 2) Create backend via Firebase Console (App Hosting) if none exists
# 3) Add GitHub secret FIREBASE_TOKEN (generated via 'firebase login:ci')
